steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/streams-api:latest'
      - '-f'
      - 'streams-api/Dockerfile'
      - '.'
    id: 'build-streams-api'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/booking-streams:latest'
      - '-f'
      - 'booking-streams/Dockerfile'
      - '.'
    id: 'build-booking-streams'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/ticket-streams:latest'
      - '-f'
      - 'ticket-streams/Dockerfile'
      - '.'
    id: 'build-ticket-streams'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/streams-api:latest'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/booking-streams:latest'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/ticket-streams:latest'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY