steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: '.'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/booking-platform:latest'
      - '-f'
      - 'booking-platform/Dockerfile'
      - '.'
    id: 'build-booking-platform-image'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/booking-platform:latest'
    id: 'push-booking-platform-image'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/booking-platform:latest'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
