steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/app:latest'
      - '.'
    id: 'build-image'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/app:latest'
    id: 'push-image'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/app:latest'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
