steps:
  # Booking app 빌드
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=booking-app/Dockerfile'
      - '--context=dir://.'
      - '--destination=asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/booking-app:latest'
      - '--cache=true'
      - '--cache-ttl=336h'
    id: 'build-booking-app'
    waitFor: ['-']

  # Streams 모듈들 (현재는 주석 처리)
  # - name: 'gcr.io/kaniko-project/executor:latest'
  #   args:
  #     - '--dockerfile=stream-api/Dockerfile'
  #     - '--context=dir://.'
  #     - '--destination=asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/stream-api:latest'
  #     - '--cache=true'
  #     - '--cache-ttl=336h'
  #   id: 'build-stream-api'
  #   waitFor: ['-']

  # - name: 'gcr.io/kaniko-project/executor:latest'
  #   args:
  #     - '--dockerfile=stream-booking/Dockerfile'
  #     - '--context=dir://.'
  #     - '--destination=asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/stream-booking:latest'
  #     - '--cache=true'
  #     - '--cache-ttl=336h'
  #   id: 'build-stream-booking'
  #   waitFor: ['-']

  # - name: 'gcr.io/kaniko-project/executor:latest'
  #   args:
  #     - '--dockerfile=stream-ticket/Dockerfile'
  #     - '--context=dir://.'
  #     - '--destination=asia-northeast3-docker.pkg.dev/$PROJECT_ID/ticket-booking/stream-ticket:latest'
  #     - '--cache=true'
  #     - '--cache-ttl=336h'
  #   id: 'build-stream-ticket'
  #   waitFor: ['-']

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'