steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean', 'build']
    id: 'gradle-build'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ticket-booking:latest',
           '-t', 'gcr.io/$PROJECT_ID/ticket-booking:$SHORT_SHA', '.']
    id: 'build-image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ticket-booking']
    id: 'push-image'

images:
  - 'gcr.io/$PROJECT_ID/ticket-booking:latest'
  - 'gcr.io/$PROJECT_ID/ticket-booking:$SHORT_SHA'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
