steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ticket-booking:latest', '.' ]
    id: 'build-image'

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/ticket-booking' ]
    id: 'push-image'

images:
  - 'gcr.io/$PROJECT_ID/ticket-booking:latest'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
