server:
  port: 8080
spring:
  application:
    name: ticket-booking-system
  datasource:
    url: jdbc:mysql://localhost:3306/booking_system?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
#  level:
#    net.javacrumbs.shedlock: debug
#    org.springframework.transaction: trace
#    com.zaxxer.hikari: debug

