server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ticket-booking-system
    instance-id: ${HOSTNAME:localhost}-${server.port:8080}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

queue:
  consumer-group: ${QUEUE_CONSUMER_GROUP:bookingGroup}
  instance-count: ${QUEUE_INSTANCE_COUNT:1}
  partition-count: ${QUEUE_PARTITION_COUNT:32}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      instance: ${spring.application.instance-id}
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/booking_system?serverTimezone=UTC&tcpKeepAlive=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/booking_system?serverTimezone=UTC&tcpKeepAlive=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
