server:
  port: 8080
spring:
  application:
    name: ticket-booking-system
  datasource:
    url: jdbc:mysql://localhost:3306/booking_system?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


